run:
  timeout: 1m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - structcheck
    - ineffassign
    - deadcode

issues:
  exclude-use-default: false
