name: Build and Release

on:
  push:
    tags:
      - 'v*'  # trigger on version tags 
      
permissions:
  contents: write # needed to publish a release

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build binaries for Linux, Windows, and macOS
        run: |
          mkdir -p dist
          
          # Linux
          GOOS=linux GOARCH=amd64 go build -o dist/lazydebrid-linux ./cmd/main.go
          
          # Windows
          GOOS=windows GOARCH=amd64 go build -o dist/lazydebrid-windows.exe ./cmd/main.go
          
          # macOS
          GOOS=darwin GOARCH=amd64 go build -o dist/lazydebrid-macos-amd64 ./cmd/main.go
          GOOS=darwin GOARCH=arm64 go build -o dist/lazydebrid-macos-arm64 ./cmd/main.go

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.2.2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
